name: deploy to lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: response-lambda
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          file_name: .env.response-lambda
      - name: Move created env file into correct directory and rename
        run: |
          mv ../.env.response-lambda .env
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: zip
        run: zip -r bundle.zip .
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-2
          function_name: micro-fracture-scan-questionnaire-response-save
          zip_file: ./response-lambda/bundle.zip
